services:
  # The Database
  db:
    image: postgres:14.21-alpine3.23
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    # Low resource tuning for your J4125
    command: postgres -c 'max_connections=100' -c 'shared_buffers=128MB'

  # The Chat Server
  mattermost:
    image: mattermost/mattermost-team-edition:11.4
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./volumes/config:/mattermost/config
      - ./volumes/data:/mattermost/data
      - ./volumes/logs:/mattermost/logs
      - ./volumes/plugins:/mattermost/plugins
      - ./volumes/client/plugins:/mattermost/client/plugins
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
    ports:
      - "8065:8065"
